name: google_book_api
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter_svg: ^2.0.10+1
  result_dart: ^1.1.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_modular: ^6.3.3
  localization: ^2.1.1
  shared_preferences: ^2.2.3
  flutter_localizations:
    sdk: flutter
  intl: any
  pretty_dio_logger: ^1.3.1
  flutter_html: ^3.0.0-beta.2
  collection: ^1.18.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.2.6
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true